include:
- project: mia-platform/pipeline-templates
  file: Application.gitlab-ci.yml
  ref: HEAD
- template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

variables:
  NODE_IMAGE_TAG: "18"
  ENABLE_DOCKER_BUILD_IN_MR: "true"
  IMAGE_NAME: mia_template_image_name_placeholder

build:
  extends: .npm-build
  stage: build

lint:
  extends: .npm-lint
  stage: sast

test:
  extends: .npm-test
  stage: test
